---
apiVersion: v1
kind: Service
metadata:
  name: test-db-0
  namespace: mongodb
  labels:
    name: mongodb
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 30017
      name: tcp
  selector:
    statefulset.kubernetes.io/pod-name: test-db-0
---
apiVersion: v1
kind: Service
metadata:
  name: test-db-1
  namespace: mongodb
  labels:
    name: mongodb
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 30018
      name: tcp
  selector:
    statefulset.kubernetes.io/pod-name: test-db-1
---
apiVersion: v1
kind: Service
metadata:
  name: test-db-2
  namespace: mongodb
  labels:
    name: mongodb
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 30019
      name: tcp
  selector:
    statefulset.kubernetes.io/pod-name: test-db-2
